# Generated by Django 3.0.7 on 2020-06-29 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscribers_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 15, 59, 16, 862196)),
        ),
    ]
