# Generated by Django 3.0.7 on 2020-06-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200629_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
